Initial Commit
Eugint11/java-filmorate pull request #1
Opened 2023-08-04 16:43 UTC by Eugint11

2023-08-09 11:04 UTC, PolnySkvorets commented on src/test/java/ru/practicum/filmorate/controller/UserControllerTest.java
> +        User user = User.builder().id(1).login("login").name("name").email("test@gmail.com").birthday(LocalDate.of(1996, 06, 11)).build();
Для форматирования попробуй такой формат записи подобных структур, так как получается слишком длинная строка
User.builder()
.id(1)
.login("login")
.name("name")
...

2023-08-09 11:06 UTC, PolnySkvorets commented on src/main/java/ru/practicum/filmorate/user/UserController.java
> +                !user.getEmail().contains("@")
Стоит добавить проверку пустой email или нет. Также проверь выравнивание, возможно здесь лишние отступы с этой строки

2023-08-09 11:08 UTC, PolnySkvorets commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
В этой задаче пока не нужна база

2023-08-09 11:08 UTC, PolnySkvorets commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:shareit
Тоже не используется

2023-08-09 11:10 UTC, PolnySkvorets commented on src/main/java/ru/practicum/filmorate/film/FilmController.java
> +    public ResponseEntity<String> postFilm(@Valid @RequestBody Film film) {
Здесь ты можешь заменить на ResponseEntity<Film>, фреймворк должен сам стерилизовать своими силами

2023-08-09 11:11 UTC, PolnySkvorets requested changes
Привет! Обрати внимание на замечание. Лишний неиспользуемый код не стоит держать в приложении

2023-08-11 15:36 UTC, Eugint11 commented on src/main/java/ru/practicum/filmorate/user/UserController.java
> +                !user.getEmail().contains("@")
В классе User есть аннотации, которые отсекают попытки отправить данные пользователя как с пустым email, так и с не указанным email. 
@NotNull @NotBlank @Email
Но дополнительно добавил проверку, если пользователь указан не через API.

Отступы же автоматически добавляет IDEA при форматировании.

2023-08-11 15:37 UTC, Eugint11 commented on src/test/java/ru/practicum/filmorate/controller/UserControllerTest.java
> +        User user = User.builder().id(1).login("login").name("name").email("test@gmail.com").birthday(LocalDate.of(1996, 06, 11)).build();
Готово

2023-08-11 15:37 UTC, Eugint11 commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
Готово

2023-08-11 15:38 UTC, Eugint11 commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:shareit
Готово

2023-08-11 15:41 UTC, Eugint11 commented on src/main/java/ru/practicum/filmorate/film/FilmController.java
> +    public ResponseEntity<String> postFilm(@Valid @RequestBody Film film) {
Готово

2023-08-12 16:16 UTC, PolnySkvorets commented on src/main/java/ru/practicum/filmorate/user/User.java
> + * TODO Sprint add-controllers.
Не оставляй тудушки, если уже написал код

2023-08-12 16:17 UTC, PolnySkvorets commented on src/main/java/ru/practicum/filmorate/film/Film.java
> +    @NotNull @Positive
Здесь у тебя примитив, поэтому аннотация notNull не нужна здесь, либо поменяй на обёртку

2023-08-12 16:17 UTC, PolnySkvorets commented on src/main/java/ru/practicum/filmorate/film/FilmController.java
> +    final int maxLengthDescription = 200;
Добавь к final полям такие же модификаторы доступа

2023-08-12 16:18 UTC, PolnySkvorets requested changes
Хорошо поправил замечания. Посмотри там немного ещё некоторых моментов нашёл

2023-08-14 10:28 UTC, Eugint11 commented on src/main/java/ru/practicum/filmorate/user/User.java
> + * TODO Sprint add-controllers.
Готово

2023-08-14 10:30 UTC, Eugint11 commented on src/main/java/ru/practicum/filmorate/film/Film.java
> +    @NotNull @Positive
Готово

2023-08-14 10:30 UTC, Eugint11 commented on src/main/java/ru/practicum/filmorate/film/FilmController.java
> +    final int maxLengthDescription = 200;
Готово

2023-08-15 10:42 UTC, PolnySkvorets approved these changes
Замечания исправлены, отлично

2023-09-07 11:43 UTC, merged